/**
 * The "INEC Result Datas" account in Data Bank, and what is kept in it.
 *
 * ══════════════════════════════════════════════════════════════════════════
 *  AN ACCOUNT OF DATA BANK'S OWN KIND, NOT SOMETHING BESIDE IT
 *
 *  Data Bank keeps each body of work as an account: a row in
 *  `dumpsite.projects` and a vault, which is a schema named `bank_<name>`.
 *  Every table in a vault is listed in `dumpsite.datasets`, and that list is
 *  what Data Bank's own screens read. This opens the account the same way
 *  Data Bank's `ensureProject` does and lists every table it makes, so what
 *  is gathered from IReV shows on Data Bank's storage board under its
 *  account, readable and exportable there, with nothing new for Data Bank to
 *  learn.
 *
 *  ── ONE ACCOUNT, EVERY ELECTION ─────────────────────────────────────────
 *  Elections are rows, not tables. A presidential election in 2023 and a
 *  governorship in 2026 sit in the same five tables, told apart by the
 *  election they belong to, so moving between years and types is a filter
 *  and adding an election the portal publishes next year needs no change.
 * ══════════════════════════════════════════════════════════════════════════
 *
 * Every function takes `db`: a function `(text, params) => rows`. The caller
 * owns the connection, which keeps this file the same under a script, a
 * request and a test.
 */

export const ACCOUNT = {
  name: "INEC Result Datas",
  slug: "inec_result_datas",
  schema: "bank_inec_result_datas",
  purpose:
    "Gathered from INEC's Result Viewing Portal (IReV): every election it publishes, " +
    "by type and year, down to each polling unit and the photograph of its result sheet.",
};

const ACTOR = "poll360-irev";

/** Raised whenever a table or column is added, so an account opened by an
    earlier version is brought up to date the next time the screen is opened. */
const SCHEMA = "7";
const V = ACCOUNT.schema;

/* `_row` is on every table because Data Bank's reader pages a dataset by it. */
const ROW = "_row bigint GENERATED BY DEFAULT AS IDENTITY";

/**
 * The tables, declared once. The statement that creates each one and the
 * column list Data Bank's board shows are both built from this.
 */
export const TABLES = {
  election_types: {
    label: "IReV election types",
    key: "code",
    columns: [
      ["code", "text"],
      ["name", "text"],
      ["type_id", "integer"],
      ["ref", "text"],
    ],
  },
  elections: {
    label: "IReV elections",
    key: "election_id",
    columns: [
      ["election_id", "integer"],
      ["ref", "text"],
      ["type_code", "text"],
      ["type_name", "text"],
      ["year", "integer"],
      ["held_on", "date"],
      ["name", "text"],
      ["state_id", "integer"],
      ["state_name", "text"],
      ["area_name", "text"],
      ["area_kind", "text"],
      /* What the portal itself says it expects and holds, and when asked. */
      ["expected_units", "integer"],
      ["sheets_up", "integer"],
      ["checked_at", "timestamptz"],
      /* Chosen to be kept up to date by the watch. */
      ["watching", "boolean", "NOT NULL DEFAULT false"],
      /* The Poll360 project whose returns this election is compared with. */
      ["project_id", "text"],
      /* Chosen to have its sheets read into figures as they arrive. */
      ["reading", "boolean", "NOT NULL DEFAULT false"],
      /* Set while a read-through of every ward is under way. A ward not read
         since this moment is still to do, so a read-through can be carried
         on by whoever turns up next: the screen, the command, another server. */
      ["pass_started_at", "timestamptz"],
      /* When every ward was last read through to the end. */
      ["gathered_at", "timestamptz"],
      ["listed_at", "timestamptz", "NOT NULL DEFAULT now()"],
    ],
  },
  lgas: {
    label: "IReV local governments",
    key: "election_id, lga_id",
    columns: [
      ["election_id", "integer"],
      ["lga_id", "integer"],
      ["ref", "text"],
      ["name", "text"],
      ["code", "text"],
      ["state_id", "integer"],
      ["state_name", "text"],
    ],
  },
  wards: {
    label: "IReV wards",
    key: "election_id, ward_id",
    columns: [
      ["election_id", "integer"],
      ["ward_id", "integer"],
      ["ref", "text"],
      ["name", "text"],
      ["code", "text"],
      ["lga_id", "integer"],
      ["state_id", "integer"],
      ["units", "integer"],
      ["sheets", "integer"],
      ["read_at", "timestamptz"],
      /* Holds a polling unit we have a return for, so it is read before the
         rest of the election. */
      ["first", "boolean", "NOT NULL DEFAULT false"],
    ],
  },
  sheets: {
    label: "IReV polling unit result sheets",
    key: "election_id, unit_id",
    columns: [
      ["election_id", "integer"],
      ["unit_id", "integer"],
      ["pu_code", "text"],
      ["unit_name", "text"],
      ["ward_id", "integer"],
      ["lga_id", "integer"],
      ["state_id", "integer"],
      /* The photograph of Form EC8A on the commission's own storage. Null
         where nothing has been uploaded for the unit. */
      ["sheet_url", "text"],
      ["sheet_at", "timestamptz"],
      /* When the commission's system received the file, from the file's own
         name. See `uploadedAt` in ./shape.js for why this and not `sheet_at`. */
      ["uploaded_at", "timestamptz"],
      ["supplement", "boolean", "NOT NULL DEFAULT false"],
      /* How many sheets were up for this unit before the present one. */
      ["earlier_sheets", "integer", "NOT NULL DEFAULT 0"],
      ["no_voters", "boolean", "NOT NULL DEFAULT false"],
      ["first_seen_at", "timestamptz", "NOT NULL DEFAULT now()"],
      ["changed_at", "timestamptz", "NOT NULL DEFAULT now()"],
    ],
  },
  readings: {
    label: "IReV result sheet figures",
    key: "election_id, unit_id",
    columns: [
      ["election_id", "integer"],
      ["unit_id", "integer"],
      ["pu_code", "text"],
      /* The sheet these figures were read from. A unit whose sheet is later
         replaced is read again, because this no longer matches. */
      ["sheet_url", "text"],
      /* read, unreadable, gone (the photograph is no longer where the portal
         says), or failed (worth another go). */
      ["status", "text"],
      /* Whether the party figures add up to accredited less rejected. This,
         not the reader's confidence, is what says a reading can be relied on. */
      ["balanced", "boolean"],
      ["problems", "text"],
      /* The unit code written on the paper, and whether it is the unit the
         portal filed the sheet under. */
      ["code_on_sheet", "text"],
      ["code_matches", "boolean"],
      ["registered", "integer"],
      ["accredited", "integer"],
      ["rejected", "integer"],
      ["valid_votes", "integer"],
      ["stated_valid", "integer"],
      /* {"APC": 120, "PDP": 98, ...}: every party row that carried a figure. */
      ["party_votes", "jsonb"],
      ["legibility", "text"],
      ["signature", "text"],
      ["stamp", "text"],
      ["alteration", "text"],
      ["reader", "text"],
      ["tokens_in", "integer"],
      ["tokens_out", "integer"],
      ["attempts", "integer", "NOT NULL DEFAULT 1"],
      ["read_at", "timestamptz", "NOT NULL DEFAULT now()"],
    ],
  },
  pictures: {
    label: "IReV result sheet picture details",
    key: "election_id, unit_id",
    columns: [
      ["election_id", "integer"],
      ["unit_id", "integer"],
      ["pu_code", "text"],
      ["sheet_url", "text"],
      /* examined, gone, or failed (worth another go). */
      ["status", "text"],
      ["kind", "text"],
      /* What took the picture, by the file's own account. */
      ["device_make", "text"],
      ["device_model", "text"],
      ["software", "text"],
      /* The device's own clock, as written: local time, no zone. */
      ["taken_at", "text"],
      /* The satellites' clock, which the device cannot be set wrong on. */
      ["satellite_at", "timestamptz"],
      ["latitude", "double precision"],
      ["longitude", "double precision"],
      ["altitude", "real"],
      /* The state and local government those coordinates fall in, and whether
         that is where the polling unit is. Null where the file has no place. */
      ["taken_state", "text"],
      ["taken_lga", "text"],
      ["place_ok", "boolean"],
      /* Days between polling day and the day in the file. Negative is before. */
      ["days_from_poll", "integer"],
      ["width", "integer"],
      ["height", "integer"],
      /* For a scanned document: what saved it, and when. */
      ["saved_with", "text"],
      ["document_at", "text"],
      /* When the commission's storage received the file. */
      ["stored_at", "timestamptz"],
      ["notes", "text"],
      ["attempts", "integer", "NOT NULL DEFAULT 1"],
      ["examined_at", "timestamptz", "NOT NULL DEFAULT now()"],
    ],
  },
  wanted: {
    label: "IReV polling units we hold returns for",
    key: "election_id, pu_code",
    columns: [
      /* The units our own agents filed from, for the election their project
         is held against. These are gathered, examined and read before any
         other, because they are the only ones there is anything to compare. */
      ["election_id", "integer"],
      ["pu_code", "text"],
    ],
  },
  follows: {
    label: "IReV years being followed",
    key: null,
    columns: [
      /* Any election the portal lists that matches is watched from the moment
         it appears. A part left empty matches everything. */
      ["year", "integer"],
      ["type_code", "text"],
      ["state_name", "text"],
      ["read_sheets", "boolean", "NOT NULL DEFAULT false"],
      ["added_at", "timestamptz", "NOT NULL DEFAULT now()"],
    ],
  },
  state: {
    label: "IReV gatherer state",
    key: "name",
    columns: [
      ["name", "text"],
      ["value", "text"],
      ["at", "timestamptz"],
    ],
  },
  runs: {
    label: "IReV gathering log",
    key: null,
    columns: [
      ["election_id", "integer"],
      ["kind", "text"],
      ["started_at", "timestamptz", "NOT NULL DEFAULT now()"],
      ["finished_at", "timestamptz"],
      ["wards_read", "integer", "NOT NULL DEFAULT 0"],
      ["units_seen", "integer", "NOT NULL DEFAULT 0"],
      ["sheets_changed", "integer", "NOT NULL DEFAULT 0"],
      ["failures", "integer", "NOT NULL DEFAULT 0"],
      ["note", "text"],
    ],
  },
};

/** The statement that creates one table. */
export function createStatement(table) {
  const spec = TABLES[table];
  const columns = spec.columns.map(([name, type, rest]) => `${name} ${type}${rest ? ` ${rest}` : ""}`);
  const key = spec.key ? `, PRIMARY KEY (${spec.key})` : "";
  return `CREATE TABLE IF NOT EXISTS ${V}.${table} (${ROW}, ${columns.join(", ")}${key})`;
}

/**
 * Open the account and everything in it. Safe to run every time: each step
 * leaves what is already there alone.
 */
export async function open(db) {
  const hub = await db(`SELECT to_regclass('dumpsite.projects') AS projects`);
  if (!hub[0]?.projects) {
    throw new Error(
      "This database has no Data Bank in it. Point DATABANK_DATABASE_URL at Data Bank's database."
    );
  }

  await db(`CREATE SCHEMA IF NOT EXISTS ${V}`);

  /* The same insert Data Bank's own ensureProject makes. */
  await db(
    `INSERT INTO dumpsite.projects (tenant_id, name, slug, schema_name, purpose, created_by)
     VALUES ('default', $1, $2, $3, $4, $5)
     ON CONFLICT (tenant_id, slug) DO NOTHING`,
    [ACCOUNT.name, ACCOUNT.slug, V, ACCOUNT.purpose, ACTOR]
  );
  const [account] = await db(
    `SELECT id, name, schema_name, created_at FROM dumpsite.projects
      WHERE tenant_id = 'default' AND slug = $1`,
    [ACCOUNT.slug]
  );

  for (const table of Object.keys(TABLES)) {
    await db(createStatement(table));
  }
  await db(`CREATE INDEX IF NOT EXISTS sheets_code_idx ON ${V}.sheets (election_id, pu_code)`);
  await db(`CREATE INDEX IF NOT EXISTS sheets_changed_idx ON ${V}.sheets (election_id, changed_at DESC)`);
  await db(`CREATE INDEX IF NOT EXISTS wards_read_idx ON ${V}.wards (election_id, read_at NULLS FIRST)`);
  await db(`CREATE UNIQUE INDEX IF NOT EXISTS follows_key ON ${V}.follows
              (coalesce(year, 0), coalesce(type_code, ''), coalesce(state_name, ''))`);

  /* Columns added since an account was first opened. Additive only, as
     everything in Data Bank is. */
  await db(`ALTER TABLE ${V}.elections ADD COLUMN IF NOT EXISTS project_id text`);
  await db(`ALTER TABLE ${V}.pictures ADD COLUMN IF NOT EXISTS stored_at timestamptz`);
  await db(`ALTER TABLE ${V}.wards ADD COLUMN IF NOT EXISTS first boolean NOT NULL DEFAULT false`);
  await db(`ALTER TABLE ${V}.sheets ADD COLUMN IF NOT EXISTS uploaded_at timestamptz`);
  await stampUploads(db);
  /* Coming up from an earlier version only: sheets examined before the time
     the commission received them was recorded are looked at once more, and
     readings that failed on a document the reader can now open are retried. */
  const before = Number((await since(db, "schema"))?.value ?? SCHEMA);
  if (before < 4) {
    await db(`DELETE FROM ${V}.pictures WHERE stored_at IS NULL AND status <> 'gone'`);
    await db(`DELETE FROM ${V}.readings WHERE status = 'failed'`);
  }
  await db(`CREATE INDEX IF NOT EXISTS pictures_spot_idx ON ${V}.pictures (election_id, latitude, longitude)`);
  /* "Every code beginning 05/16" is a search by the start of a text, which an
     ordinary index does not serve. These two do. */
  await db(`CREATE INDEX IF NOT EXISTS sheets_place_idx ON ${V}.sheets (election_id, pu_code text_pattern_ops)`);
  await db(`CREATE INDEX IF NOT EXISTS readings_place_idx ON ${V}.readings (election_id, pu_code text_pattern_ops)`);

  /* List each table on Data Bank's board, once. */
  for (const [table, spec] of Object.entries(TABLES)) {
    const columns = spec.columns.map(([name, type]) => ({ source: name, name, type }));
    await db(
      `INSERT INTO dumpsite.datasets
         (tenant_id, project_id, name, kind, table_schema, table_name, columns, rows, created_by)
       SELECT 'default', $1, $2, 'REST_API', $3, $4, $5::jsonb, 0, $6
        WHERE NOT EXISTS (
          SELECT 1 FROM dumpsite.datasets WHERE table_schema = $3 AND table_name = $4
        )`,
      [account.id, spec.label, V, table, JSON.stringify(columns), ACTOR]
    );
    await db(`UPDATE dumpsite.datasets SET columns = $3::jsonb WHERE table_schema = $1 AND table_name = $2`, [
      V,
      table,
      JSON.stringify(columns),
    ]);
  }

  /* And the portal as a source on the paying-in counter. */
  await db(
    `INSERT INTO dumpsite.connections (tenant_id, project_id, kind, name, endpoint, resource, created_by)
     SELECT 'default', $1, 'REST_API', 'INEC IReV', $2, 'election-types', $3
      WHERE NOT EXISTS (
        SELECT 1 FROM dumpsite.connections WHERE project_id = $1 AND name = 'INEC IReV'
      )`,
    [account.id, "https://www.inecelectionresults.ng/", ACTOR]
  );

  await mark(db, "schema", SCHEMA);
  return account;
}

/**
 * Give every sheet held the time in its own file name, where it has one and
 * it has not been taken yet. The same rule as `uploadedAt` in ./shape.js,
 * said to the database, for sheets gathered before the time was kept.
 */
export async function stampUploads(db, electionId = null) {
  /* The file's name, and the first ten digits standing alone in it. 15 to 19
     at the front keeps it to 2017–2033 before the range below is applied. */
  const stamp = `to_timestamp(substring(regexp_replace(split_part(sheet_url, '?', 1), '^.*/', '')
                   from '(?:^|[^0-9])(1[5-9][0-9]{8})(?:[^0-9]|$)')::bigint)`;
  await db(
    `UPDATE ${V}.sheets
        SET uploaded_at = ${stamp}
      WHERE uploaded_at IS NULL AND sheet_url IS NOT NULL
        AND ($1::int IS NULL OR election_id = $1)
        AND ${stamp} BETWEEN timestamptz '2019-01-01' AND now() + interval '1 day'`,
    [electionId]
  );
}

/* ── WRITING ──────────────────────────────────────────────────────────────
   Every write sends whole columns as arrays and lets the database unnest
   them, so a ward of forty units is one statement rather than forty. */

const column = (rows, name) => rows.map((row) => row[name] ?? null);

export async function saveTypes(db, rows) {
  if (!rows.length) return;
  await db(
    `INSERT INTO ${V}.election_types (code, name, type_id, ref)
     SELECT * FROM unnest($1::text[], $2::text[], $3::int[], $4::text[])
     ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, type_id = EXCLUDED.type_id, ref = EXCLUDED.ref`,
    ["code", "name", "type_id", "ref"].map((name) => column(rows, name))
  );
}

export async function saveElections(db, rows) {
  if (!rows.length) return;
  await db(
    `INSERT INTO ${V}.elections
       (election_id, ref, type_code, type_name, year, held_on, name, state_id, state_name, area_name, area_kind)
     SELECT * FROM unnest($1::int[], $2::text[], $3::text[], $4::text[], $5::int[], $6::date[],
                          $7::text[], $8::int[], $9::text[], $10::text[], $11::text[])
     ON CONFLICT (election_id) DO UPDATE SET
       ref = EXCLUDED.ref, type_code = EXCLUDED.type_code, type_name = EXCLUDED.type_name,
       year = EXCLUDED.year, held_on = EXCLUDED.held_on, name = EXCLUDED.name,
       state_id = EXCLUDED.state_id, state_name = EXCLUDED.state_name,
       area_name = EXCLUDED.area_name, area_kind = EXCLUDED.area_kind`,
    [
      "election_id", "ref", "type_code", "type_name", "year", "held_on",
      "name", "state_id", "state_name", "area_name", "area_kind",
    ].map((name) => column(rows, name))
  );
}

export async function savePlaces(db, { lgas, wards }) {
  if (lgas.length) {
    await db(
      `INSERT INTO ${V}.lgas (election_id, lga_id, ref, name, code, state_id, state_name)
       SELECT * FROM unnest($1::int[], $2::int[], $3::text[], $4::text[], $5::text[], $6::int[], $7::text[])
       ON CONFLICT (election_id, lga_id) DO UPDATE SET
         ref = EXCLUDED.ref, name = EXCLUDED.name, code = EXCLUDED.code,
         state_id = EXCLUDED.state_id, state_name = EXCLUDED.state_name`,
      ["election_id", "lga_id", "ref", "name", "code", "state_id", "state_name"].map((name) => column(lgas, name))
    );
  }

  /* Wards go in a few thousand at a time: a nationwide election has 8,809. */
  for (let at = 0; at < wards.length; at += 2000) {
    const slice = wards.slice(at, at + 2000);
    await db(
      `INSERT INTO ${V}.wards (election_id, ward_id, ref, name, code, lga_id, state_id)
       SELECT * FROM unnest($1::int[], $2::int[], $3::text[], $4::text[], $5::text[], $6::int[], $7::int[])
       ON CONFLICT (election_id, ward_id) DO UPDATE SET
         ref = EXCLUDED.ref, name = EXCLUDED.name, code = EXCLUDED.code,
         lga_id = EXCLUDED.lga_id, state_id = EXCLUDED.state_id`,
      ["election_id", "ward_id", "ref", "name", "code", "lga_id", "state_id"].map((name) => column(slice, name))
    );
  }
}

/**
 * Save polling units and their sheets, and say what was new.
 *
 * A row is written only where something about the sheet differs from what is
 * held, so reading the same ward twice changes nothing and `changed_at` means
 * what it says. Returns how many units were new to the vault and how many
 * sheets went up or were replaced.
 */
export async function saveSheets(db, rows) {
  if (!rows.length) return { units: 0, sheets: 0 };

  const written = await db(
    `INSERT INTO ${V}.sheets AS held
       (election_id, unit_id, pu_code, unit_name, ward_id, lga_id, state_id,
        sheet_url, sheet_at, supplement, earlier_sheets, no_voters, uploaded_at)
     SELECT * FROM unnest($1::int[], $2::int[], $3::text[], $4::text[], $5::int[], $6::int[], $7::int[],
                          $8::text[], $9::timestamptz[], $10::boolean[], $11::int[], $12::boolean[],
                          $13::timestamptz[])
     ON CONFLICT (election_id, unit_id) DO UPDATE SET
       pu_code = EXCLUDED.pu_code, unit_name = EXCLUDED.unit_name,
       ward_id = COALESCE(EXCLUDED.ward_id, held.ward_id),
       lga_id = COALESCE(EXCLUDED.lga_id, held.lga_id),
       state_id = COALESCE(EXCLUDED.state_id, held.state_id),
       sheet_url = EXCLUDED.sheet_url, sheet_at = EXCLUDED.sheet_at,
       supplement = EXCLUDED.supplement, earlier_sheets = EXCLUDED.earlier_sheets,
       no_voters = EXCLUDED.no_voters, uploaded_at = EXCLUDED.uploaded_at, changed_at = now()
     WHERE (held.sheet_url, held.sheet_at, held.earlier_sheets)
           IS DISTINCT FROM (EXCLUDED.sheet_url, EXCLUDED.sheet_at, EXCLUDED.earlier_sheets)
     RETURNING (xmax = 0) AS fresh, sheet_url IS NOT NULL AS up`,
    [
      "election_id", "unit_id", "pu_code", "unit_name", "ward_id", "lga_id", "state_id",
      "sheet_url", "sheet_at", "supplement", "earlier_sheets", "no_voters", "uploaded_at",
    ].map((name) => column(rows, name))
  );

  return {
    units: written.filter((row) => row.fresh).length,
    sheets: written.filter((row) => row.up).length,
  };
}

/** Mark one ward read, with what was found in it. */
export async function wardRead(db, electionId, wardId, { units, sheets }) {
  await db(
    `UPDATE ${V}.wards SET units = $3, sheets = $4, read_at = now()
      WHERE election_id = $1 AND ward_id = $2`,
    [electionId, wardId, units, sheets]
  );
}

/** What the portal itself reports for an election, written beside it. */
export async function portalCount(db, electionId, stats) {
  await db(
    `UPDATE ${V}.elections
        SET expected_units = $2, sheets_up = $3, checked_at = now()
      WHERE election_id = $1`,
    [electionId, stats?.pus ?? null, stats?.documents ?? null]
  );
}

export async function setWatching(db, electionIds, watching) {
  if (!electionIds.length) return;
  await db(`UPDATE ${V}.elections SET watching = $2 WHERE election_id = ANY($1::int[])`, [
    electionIds,
    watching,
  ]);
}

export async function logRun(db, run) {
  await db(
    `INSERT INTO ${V}.runs
       (election_id, kind, started_at, finished_at, wards_read, units_seen, sheets_changed, failures, note)
     VALUES ($1, $2, $3, now(), $4, $5, $6, $7, $8)`,
    [
      run.electionId,
      run.kind,
      run.startedAt,
      run.wardsRead ?? 0,
      run.unitsSeen ?? 0,
      run.sheetsChanged ?? 0,
      run.failures ?? 0,
      run.note ?? null,
    ]
  );
}

/* ── A READ-THROUGH, DONE IN STEPS ──────────────────────────────────────── */

/** Begin reading an election through. Leaves one already under way alone. */
export async function startPass(db, electionId) {
  await db(
    `UPDATE ${V}.elections SET pass_started_at = now()
      WHERE election_id = $1 AND pass_started_at IS NULL`,
    [electionId]
  );
}

/** Wards of an election not yet read in the read-through under way. */
export async function wardsLeft(db, electionId, limit = null) {
  return db(
    `SELECT w.ward_id, w.ref, w.name
       FROM ${V}.wards w JOIN ${V}.elections e ON e.election_id = w.election_id
      WHERE w.election_id = $1 AND e.pass_started_at IS NOT NULL
        AND (w.read_at IS NULL OR w.read_at < e.pass_started_at)
      ORDER BY w.first DESC, w.read_at NULLS FIRST, w.ward_id
      LIMIT $2`,
    [electionId, limit]
  );
}

/* ── OUR OWN POLLING UNITS FIRST ────────────────────────────────────────────
   An election is read through ward by ward, and a nationwide one is 8,809
   wards. The only polling units there is anything to hold INEC's sheet
   against are the ones we filed a return from — a few hundred of them — and
   in ward order they could be reached at any point in a two-hour read-through.
   So they are named here, their wards are read before every other ward, and
   their sheets are examined and read before every other sheet. */

/** Name the polling units we hold returns for. Replaces the list held. */
export async function setWanted(db, electionId, codes) {
  const unique = [...new Set(codes.map((code) => String(code ?? "").trim()).filter(Boolean))];
  await db(`DELETE FROM ${V}.wanted WHERE election_id = $1 AND NOT (pu_code = ANY($2::text[]))`, [electionId, unique]);
  if (unique.length) {
    await db(
      `INSERT INTO ${V}.wanted (election_id, pu_code)
       SELECT $1, code FROM unnest($2::text[]) AS code
       ON CONFLICT DO NOTHING`,
      [electionId, unique]
    );
  }
  return unique.length;
}

/**
 * Mark the wards that hold a wanted unit, so they are read first.
 *
 * A ward's place in a unit's code is state/local government/ward, and the
 * portal files a ward under ids of its own. `states` joins the two: each
 * state's name as the portal spells it, with the two-digit number its codes
 * begin with.
 */
export async function prioritise(db, electionId, states) {
  await db(
    `UPDATE ${V}.wards w
        SET first = EXISTS (
          SELECT 1
            FROM ${V}.wanted x
            JOIN ${V}.lgas l ON l.election_id = w.election_id AND l.lga_id = w.lga_id
            JOIN unnest($2::text[], $3::text[]) AS st(name, number) ON st.name = l.state_name
           WHERE x.election_id = w.election_id
             AND left(x.pu_code, 8) = st.number || '/' || lpad(l.code, 2, '0') || '/' || lpad(w.code, 2, '0'))
      WHERE w.election_id = $1`,
    [electionId, states.map((state) => state.name), states.map((state) => state.number)]
  );
}

/** The state names the portal uses for an election, to be matched to their numbers. */
export async function stateNames(db, electionId) {
  return (await db(`SELECT DISTINCT state_name FROM ${V}.lgas WHERE election_id = $1 AND state_name IS NOT NULL`, [electionId])).map(
    (row) => row.state_name
  );
}

/** How far along an election is, and how far along our own units are within it. */
export async function progress(db, electionId) {
  const [row] = await db(
    `SELECT (SELECT count(*)::int FROM ${V}.wards WHERE election_id = $1) AS wards,
            (SELECT count(*)::int FROM ${V}.wards w JOIN ${V}.elections e USING (election_id)
              WHERE w.election_id = $1 AND e.pass_started_at IS NOT NULL
                AND (w.read_at IS NULL OR w.read_at < e.pass_started_at)) AS wards_left,
            (SELECT count(*)::int FROM ${V}.wanted WHERE election_id = $1) AS ours,
            (SELECT count(*)::int FROM ${V}.wanted x JOIN ${V}.sheets s USING (election_id, pu_code)
              WHERE x.election_id = $1) AS ours_found,
            (SELECT count(*)::int FROM ${V}.wanted x JOIN ${V}.sheets s USING (election_id, pu_code)
              WHERE x.election_id = $1 AND s.sheet_url IS NOT NULL) AS ours_up,
            (SELECT count(*)::int FROM ${V}.wanted x JOIN ${V}.readings r USING (election_id, pu_code)
              WHERE x.election_id = $1 AND r.status = 'read') AS ours_read`,
    [electionId]
  );
  return row ?? null;
}

export async function wardCount(db, electionId) {
  const [row] = await db(`SELECT count(*)::int AS n FROM ${V}.wards WHERE election_id = $1`, [electionId]);
  return row?.n ?? 0;
}

export async function finishPass(db, electionId) {
  await db(
    `UPDATE ${V}.elections SET gathered_at = now(), pass_started_at = NULL WHERE election_id = $1`,
    [electionId]
  );
}

export async function sheetsHeld(db, electionId) {
  const [row] = await db(
    `SELECT count(*)::int AS n FROM ${V}.sheets WHERE election_id = $1 AND sheet_url IS NOT NULL`,
    [electionId]
  );
  return row?.n ?? 0;
}

/* ── FOLLOWING A YEAR ───────────────────────────────────────────────────── */

export async function follow(db, { year = null, type = null, state = null, readSheets = false }) {
  await db(
    `INSERT INTO ${V}.follows (year, type_code, state_name, read_sheets)
     VALUES ($1, $2, $3, $4)
     ON CONFLICT (coalesce(year, 0), coalesce(type_code, ''), coalesce(state_name, ''))
     DO UPDATE SET read_sheets = EXCLUDED.read_sheets`,
    [year, type, state ? String(state).toUpperCase() : null, readSheets]
  );
}

export async function unfollow(db, row) {
  await db(`DELETE FROM ${V}.follows WHERE _row = $1`, [row]);
}

export async function follows(db) {
  return db(`SELECT _row, year, type_code, state_name, read_sheets, added_at FROM ${V}.follows ORDER BY year, type_code`);
}

/**
 * Start watching every listed election a follow matches and that is not
 * watched yet, and begin reading each one through. Returns the new ones.
 */
export async function applyFollows(db) {
  return db(
    `UPDATE ${V}.elections e
        SET watching = true, pass_started_at = coalesce(e.pass_started_at, now()),
            reading = e.reading OR f.read_sheets
       FROM ${V}.follows f
      WHERE NOT e.watching
        AND (f.year IS NULL OR f.year = e.year)
        AND (f.type_code IS NULL OR f.type_code = e.type_code)
        AND (f.state_name IS NULL OR f.state_name = upper(e.state_name))
      RETURNING e.election_id, e.name`
  );
}

/* ── ONE GATHERER AT A TIME ─────────────────────────────────────────────── */

/**
 * Take the turn, or learn that somebody else has it.
 *
 * The screen left open in two windows, the command running on a machine and
 * a server answering a health check may all try to gather at once. A row with
 * an expiry settles it: whoever moves the expiry forward has the turn, and a
 * holder that dies simply stops renewing it. A session lock would be tidier
 * and does not survive a pooled connection.
 */
export async function takeTurn(db, seconds = 120) {
  await db(`INSERT INTO ${V}.state (name, at) VALUES ('turn', 'epoch') ON CONFLICT (name) DO NOTHING`);
  const taken = await db(
    `UPDATE ${V}.state SET at = now() + make_interval(secs => $1)
      WHERE name = 'turn' AND at < now() RETURNING name`,
    [seconds]
  );
  return taken.length === 1;
}

export async function endTurn(db) {
  await db(`UPDATE ${V}.state SET at = 'epoch' WHERE name = 'turn'`);
}

export async function mark(db, name, value = null) {
  await db(
    `INSERT INTO ${V}.state (name, value, at) VALUES ($1, $2, now())
     ON CONFLICT (name) DO UPDATE SET value = EXCLUDED.value, at = now()`,
    [name, value]
  );
}

/** Seconds since something was last marked, or null where it never was. */
export async function since(db, name) {
  const [row] = await db(
    `SELECT extract(epoch FROM now() - at)::int AS seconds, value FROM ${V}.state WHERE name = $1`,
    [name]
  );
  return row ?? null;
}

/* ── THE FIGURES READ OFF THE SHEETS ────────────────────────────────────── */

/**
 * Sheets with nothing read from them yet: never read, replaced since, or
 * failed fewer than three times. Newest uploads first, so on the night the
 * figures follow the sheets.
 */
export async function sheetsToRead(db, electionId, limit) {
  return db(
    `SELECT s.election_id, s.unit_id, s.pu_code, s.sheet_url, coalesce(r.attempts, 0) AS attempts
       FROM ${V}.sheets s
       LEFT JOIN ${V}.readings r ON r.election_id = s.election_id AND r.unit_id = s.unit_id
      WHERE s.election_id = $1 AND s.sheet_url IS NOT NULL
        AND (r.unit_id IS NULL OR r.sheet_url IS DISTINCT FROM s.sheet_url
             OR (r.status = 'failed' AND r.attempts < 6))
      ORDER BY EXISTS (SELECT 1 FROM ${V}.wanted x
                        WHERE x.election_id = s.election_id AND x.pu_code = s.pu_code) DESC,
               /* One that failed goes to the back, so a sheet the storage will not
                  hand over cannot hold up every sheet behind it. */
               coalesce(r.attempts, 0),
               s.sheet_at DESC NULLS LAST
      LIMIT $2`,
    [electionId, limit]
  );
}

export async function saveReading(db, reading) {
  const names = [
    "election_id", "unit_id", "pu_code", "sheet_url", "status", "balanced", "problems",
    "code_on_sheet", "code_matches", "registered", "accredited", "rejected", "valid_votes",
    "stated_valid", "party_votes", "legibility", "signature", "stamp", "alteration",
    "reader", "tokens_in", "tokens_out", "attempts",
  ];
  const values = names.map((name) =>
    name === "party_votes" && reading.party_votes ? JSON.stringify(reading.party_votes) : (reading[name] ?? null)
  );
  values[names.indexOf("attempts")] = reading.attempts ?? 1;

  await db(
    `INSERT INTO ${V}.readings (${names.join(", ")})
     VALUES (${names.map((_, index) => `$${index + 1}`).join(", ")})
     ON CONFLICT (election_id, unit_id) DO UPDATE SET
       ${names.slice(2).map((name) => `${name} = EXCLUDED.${name}`).join(", ")}, read_at = now()`,
    values
  );
}

export async function setReading(db, electionIds, reading) {
  if (!electionIds.length) return;
  await db(`UPDATE ${V}.elections SET reading = $2 WHERE election_id = ANY($1::int[])`, [electionIds, reading]);
}

/* ── READING BACK ───────────────────────────────────────────────────────── */

export async function elections(db) {
  return db(
    `SELECT e.*, to_char(e.held_on, 'YYYY-MM-DD') AS held_on,
            coalesce(s.units, 0) AS units_held, coalesce(s.sheets, 0) AS sheets_held,
            coalesce(w.wards, 0) AS wards, coalesce(w.wards_left, 0) AS wards_left,
            coalesce(r.figures, 0) AS figures_read, coalesce(r.balanced, 0) AS figures_balanced,
            coalesce(p.examined, 0) AS pictures_examined
       FROM ${V}.elections e
       LEFT JOIN (SELECT election_id, count(*)::int AS units, count(sheet_url)::int AS sheets
                    FROM ${V}.sheets GROUP BY 1) s USING (election_id)
       LEFT JOIN (SELECT w.election_id, count(*)::int AS wards,
                         count(*) FILTER (WHERE x.pass_started_at IS NOT NULL
                           AND (w.read_at IS NULL OR w.read_at < x.pass_started_at))::int AS wards_left
                    FROM ${V}.wards w JOIN ${V}.elections x USING (election_id) GROUP BY 1) w USING (election_id)
       LEFT JOIN (SELECT election_id, count(*) FILTER (WHERE status = 'read')::int AS figures,
                         count(*) FILTER (WHERE balanced)::int AS balanced
                    FROM ${V}.readings GROUP BY 1) r USING (election_id)
       LEFT JOIN (SELECT election_id, count(*)::int AS examined
                    FROM ${V}.pictures GROUP BY 1) p USING (election_id)
      ORDER BY e.held_on DESC NULLS LAST, e.name`
  );
}

export async function election(db, electionId) {
  const [row] = await db(
    `SELECT e.*, to_char(e.held_on, 'YYYY-MM-DD') AS held_on FROM ${V}.elections e WHERE e.election_id = $1`,
    [electionId]
  );
  return row ?? null;
}

/** Is the account open? Asked by the screen before it reads anything else. */
export async function opened(db) {
  const [row] = await db(`SELECT to_regclass('${V}.state') AS t`);
  return Boolean(row?.t);
}

/**
 * Open and up to date? An account opened by an earlier version of this code
 * is given the tables and columns added since, once, the first time a screen
 * asks.
 */
export async function ready(db) {
  if (!(await opened(db))) return false;
  if ((await since(db, "schema"))?.value !== SCHEMA) await open(db);
  return true;
}

/* ── WHAT THE FILES SAY ABOUT THEMSELVES ────────────────────────────────── */

/** Sheets whose own file has not been looked at yet, or has changed since. */
export async function sheetsToExamine(db, electionId, limit) {
  return db(
    `SELECT s.election_id, s.unit_id, s.pu_code, s.sheet_url, s.lga_id, coalesce(p.attempts, 0) AS attempts
       FROM ${V}.sheets s
       LEFT JOIN ${V}.pictures p ON p.election_id = s.election_id AND p.unit_id = s.unit_id
      WHERE s.election_id = $1 AND s.sheet_url IS NOT NULL
        AND (p.unit_id IS NULL OR p.sheet_url IS DISTINCT FROM s.sheet_url
             OR (p.status = 'failed' AND p.attempts < 6))
      ORDER BY EXISTS (SELECT 1 FROM ${V}.wanted x
                        WHERE x.election_id = s.election_id AND x.pu_code = s.pu_code) DESC,
               coalesce(p.attempts, 0),
               s.sheet_at DESC NULLS LAST
      LIMIT $2`,
    [electionId, limit]
  );
}

const PICTURE = [
  "election_id", "unit_id", "pu_code", "sheet_url", "status", "kind", "device_make", "device_model",
  "software", "taken_at", "satellite_at", "latitude", "longitude", "altitude", "taken_state", "taken_lga",
  "place_ok", "days_from_poll", "width", "height", "saved_with", "document_at", "stored_at", "notes", "attempts",
];

export async function savePicture(db, picture) {
  await db(
    `INSERT INTO ${V}.pictures (${PICTURE.join(", ")})
     VALUES (${PICTURE.map((_, index) => `$${index + 1}`).join(", ")})
     ON CONFLICT (election_id, unit_id) DO UPDATE SET
       ${PICTURE.slice(2).map((name) => `${name} = EXCLUDED.${name}`).join(", ")}, examined_at = now()`,
    PICTURE.map((name) => (name === "attempts" ? (picture.attempts ?? 1) : (picture[name] ?? null)))
  );
}

/** The local governments of an election, for naming where a unit is. */
export async function lgas(db, electionId) {
  return db(`SELECT lga_id, name, state_name FROM ${V}.lgas WHERE election_id = $1 ORDER BY name`, [electionId]);
}

/* ── ONE ELECTION, UNIT BY UNIT ─────────────────────────────────────────── */

/* ── WHAT CAN BE WRONG WITH A POLLING UNIT'S SHEET ──────────────────────────
   Said once, here, as the test the database applies, so the list of polling
   units, the totals by place and the verification screen can never count the
   same fault three different ways.

   Each is a fact about what INEC published, not a verdict on anybody. A sheet
   that went up four days late is late; why is for a person to find out.

   `day` is the placeholder holding polling day wherever one is needed. */

/** A sheet is called late from this many days after polling day. Counting at a
    collation centre runs through the night, so the day after is ordinary. */
export const LATE_DAYS = 2;

/** Days from polling day to the day a sheet went up, on a Lagos calendar. */
const daysAfter = (day) => `((s.uploaded_at AT TIME ZONE 'Africa/Lagos')::date - ${day}::date)`;

/** An address with no file in it: "https://storage.example/" and nothing after. */
const NO_FILE = "(s.sheet_url ~ '^https?://[^/]+/?$')";
const SOUND_READING = "r.status = 'read' AND r.balanced IS TRUE AND r.code_matches IS NOT FALSE";
const ODD = "(p.place_ok IS FALSE OR p.days_from_poll < 0 OR p.days_from_poll > 1)";

export const FAULTS = {
  /* A unit INEC itself lists as having no voters is not missing a sheet. */
  missing: () => "(s.sheet_url IS NULL AND NOT s.no_voters)",
  late: (day) => `(${daysAfter(day)} >= ${LATE_DAYS})`,
  replaced: () => "(s.earlier_sheets > 0)",
  /* Listed as up, and not there: the file has left the commission's storage,
     or the address the portal gives is the storage's front door with no file
     named in it at all. */
  gone: () => `(p.status = 'gone' OR r.status = 'gone' OR ${NO_FILE})`,
  unreadable: () => "(r.status = 'unreadable')",
  doubt: () => `(r.status = 'read' AND NOT (${SOUND_READING}))`,
  wrong_paper: () => "(r.status = 'read' AND r.code_matches IS FALSE)",
  overvote: () => `(${SOUND_READING} AND (r.valid_votes > r.accredited
                     OR (r.registered IS NOT NULL AND r.accredited > r.registered)))`,
  odd_picture: () => ODD,
};

/**
 * The faults that say something is wrong with a sheet itself. Not the ones
 * about publishing — a sheet that is absent, late, or listed with no file —
 * which run to tens of thousands and are counted and listed on their own.
 */
export const GRAVE = ["odd_picture", "wrong_paper", "overvote", "replaced"];

/** The faults by name, in the order they are counted and shown. */
export const FAULT_NAMES = Object.keys(FAULTS);

const SHOWN = {
  all: () => "true",
  up: () => "s.sheet_url IS NOT NULL",
  read: () => "r.status = 'read'",
  unread: () => "s.sheet_url IS NOT NULL AND r.unit_id IS NULL",
  flagged: FAULTS.odd_picture,
  ...FAULTS,
};

/** The views a list of polling units can be narrowed to. */
export const VIEWS = Object.keys(SHOWN);

/**
 * A page of an election's polling units, with what is held about each.
 *
 * `under` narrows it to a place by the start of the unit code ("05/16"), the
 * same way the verification screen names one. `heldOn` is polling day, which
 * "late" is measured from.
 */
export async function units(db, electionId, { show = "all", lga = null, q = null, under = null, heldOn = null, limit = 50, offset = 0 } = {}) {
  const where = `s.election_id = $1 AND ${(SHOWN[show] ?? SHOWN.all)("$5")}
    AND ($2::int IS NULL OR s.lga_id = $2)
    AND ($3::text IS NULL OR s.pu_code ILIKE $3 OR s.unit_name ILIKE $3)
    AND ($4::text IS NULL OR s.pu_code LIKE $4)
    AND ($5::date IS NULL OR true)`;
  const params = [electionId, lga, q ? `%${q}%` : null, under ? `${under}%` : null, heldOn];
  const from = `${V}.sheets s
       LEFT JOIN ${V}.readings r ON r.election_id = s.election_id AND r.unit_id = s.unit_id
       LEFT JOIN ${V}.pictures p ON p.election_id = s.election_id AND p.unit_id = s.unit_id`;

  const [rows, [total]] = await Promise.all([
    db(
      `SELECT s.unit_id, s.pu_code, s.unit_name, s.sheet_url, s.sheet_at, s.earlier_sheets,
              s.uploaded_at, s.no_voters, ${daysAfter("$5")} AS days_after,
              l.name AS lga_name, w.name AS ward_name,
              r.status AS read_status, r.balanced, r.code_matches, r.accredited, r.valid_votes, r.party_votes,
              p.status AS picture_status, p.device_model, p.taken_at, p.stored_at, p.taken_lga, p.taken_state,
              p.place_ok, p.days_from_poll, p.latitude
         FROM ${from}
         LEFT JOIN ${V}.lgas l ON l.election_id = s.election_id AND l.lga_id = s.lga_id
         LEFT JOIN ${V}.wards w ON w.election_id = s.election_id AND w.ward_id = s.ward_id
        WHERE ${where}
        ORDER BY s.pu_code
        LIMIT ${Number(limit) || 50} OFFSET ${Number(offset) || 0}`,
      params
    ),
    db(`SELECT count(*)::int AS n FROM ${from} WHERE ${where}`, params),
  ]);

  return { rows, total: total?.n ?? 0 };
}

/**
 * Of the units a page is showing, which still need their picture examined or
 * their sheet read. A sheet that failed three times is not asked for again.
 */
export async function unitsToPrepare(db, electionId, unitIds) {
  return db(
    `SELECT s.election_id, s.unit_id, s.pu_code, s.sheet_url, l.state_name,
            coalesce(p.attempts, 0) AS attempts, coalesce(r.attempts, 0) AS read_attempts,
            (p.unit_id IS NULL OR p.sheet_url IS DISTINCT FROM s.sheet_url
               OR (p.status = 'failed' AND p.attempts < 3)) AS needs_examining,
            (r.unit_id IS NULL OR r.sheet_url IS DISTINCT FROM s.sheet_url
               OR (r.status = 'failed' AND r.attempts < 3)) AS needs_reading
       FROM ${V}.sheets s
       LEFT JOIN ${V}.pictures p ON p.election_id = s.election_id AND p.unit_id = s.unit_id
       LEFT JOIN ${V}.readings r ON r.election_id = s.election_id AND r.unit_id = s.unit_id
       LEFT JOIN ${V}.lgas l ON l.election_id = s.election_id AND l.lga_id = s.lga_id
      WHERE s.election_id = $1 AND s.unit_id = ANY($2::int[]) AND s.sheet_url IS NOT NULL`,
    [electionId, unitIds]
  );
}

/** How many units fall under each of the views above. */
export async function unitCounts(db, electionId, heldOn = null) {
  const [row] = await db(
    `SELECT ${Object.entries(SHOWN)
      .map(([name, test]) => `count(*) FILTER (WHERE ${test("$2")})::int AS ${name}`)
      .join(", ")},
            count(p.unit_id) FILTER (WHERE p.status = 'examined')::int AS examined,
            count(p.latitude)::int AS located
       FROM ${V}.sheets s
       LEFT JOIN ${V}.readings r ON r.election_id = s.election_id AND r.unit_id = s.unit_id
       LEFT JOIN ${V}.pictures p ON p.election_id = s.election_id AND p.unit_id = s.unit_id
      WHERE s.election_id = $1 AND ($2::date IS NULL OR true)`,
    [electionId, heldOn]
  );
  return row ?? {};
}

/** Everything held about one polling unit. */
export async function unit(db, electionId, unitId) {
  const [row] = await db(
    `SELECT s.*, l.name AS lga_name, l.state_name, w.name AS ward_name,
            to_jsonb(r) AS reading, to_jsonb(p) AS picture
       FROM ${V}.sheets s
       LEFT JOIN ${V}.readings r ON r.election_id = s.election_id AND r.unit_id = s.unit_id
       LEFT JOIN ${V}.pictures p ON p.election_id = s.election_id AND p.unit_id = s.unit_id
       LEFT JOIN ${V}.lgas l ON l.election_id = s.election_id AND l.lga_id = s.lga_id
       LEFT JOIN ${V}.wards w ON w.election_id = s.election_id AND w.ward_id = s.ward_id
      WHERE s.election_id = $1 AND s.unit_id = $2`,
    [electionId, unitId]
  );
  return row ?? null;
}

/** How many other units of the election were photographed on the same spot. */
export async function sameSpot(db, electionId, picture) {
  if (!picture || picture.latitude == null) return 0;
  const [row] = await db(
    `SELECT count(*)::int AS n FROM ${V}.pictures
      WHERE election_id = $1 AND unit_id <> $2
        AND abs(latitude - $3) < 0.0005 AND abs(longitude - $4) < 0.0005`,
    [electionId, picture.unit_id, picture.latitude, picture.longitude]
  );
  return row?.n ?? 0;
}

/** Where every located sheet of an election was photographed. */
export async function spots(db, electionId, limit = 3000) {
  return db(
    `SELECT unit_id, latitude, longitude FROM ${V}.pictures
      WHERE election_id = $1 AND latitude IS NOT NULL LIMIT $2`,
    [electionId, limit]
  );
}

/* ── ONE ELECTION, ADDED UP BY PLACE ────────────────────────────────────────
   A polling unit's code is its address: state/local government/ward/unit. So
   "every unit in Bauchi" is every code beginning 05, and adding up by place
   is grouping by how much of the code is kept — two characters for a state,
   five for a local government, eight for a ward, all of it for a unit. The
   same codes Poll360's own returns are filed under, which is what lets the
   two be held side by side without a table to translate between them. */

/** A reading that can be relied on: it adds up, and it is this unit's paper. */
const SOUND = SOUND_READING;

/**
 * Everything under one place, grouped one step down.
 *
 * `under` is the code so far ("" for the country, "05", "05/16", "05/16/01")
 * and `width` how much of each unit's code names the next step. `heldOn` is
 * polling day. Every fault in FAULTS comes back as a count under its own name.
 */
export async function placeTotals(db, electionId, under, width, heldOn = null) {
  return db(
    `SELECT left(s.pu_code, $2) AS key,
            min(l.name) AS lga_name, min(w.name) AS ward_name,
            min(s.unit_name) AS unit_name, min(s.unit_id) AS unit_id,
            count(*)::int AS units,
            count(s.sheet_url)::int AS sheets,
            count(*) FILTER (WHERE s.no_voters)::int AS no_voters,
            count(s.uploaded_at)::int AS timed,
            count(*) FILTER (WHERE r.status = 'read')::int AS read,
            count(*) FILTER (WHERE ${SOUND})::int AS sound,
            count(*) FILTER (WHERE ${FAULT_NAMES.map((name) => FAULTS[name]("$4")).join(" OR ")})::int AS faulty,
            ${FAULT_NAMES.map((name) => `count(*) FILTER (WHERE ${FAULTS[name]("$4")})::int AS ${name}`).join(",\n            ")},
            coalesce(sum(r.registered) FILTER (WHERE ${SOUND}), 0)::int AS registered,
            coalesce(sum(r.accredited) FILTER (WHERE ${SOUND}), 0)::int AS accredited,
            coalesce(sum(r.rejected) FILTER (WHERE ${SOUND}), 0)::int AS rejected,
            coalesce(sum(r.valid_votes) FILTER (WHERE ${SOUND}), 0)::int AS valid
       FROM ${V}.sheets s
       LEFT JOIN ${V}.readings r ON r.election_id = s.election_id AND r.unit_id = s.unit_id
       LEFT JOIN ${V}.pictures p ON p.election_id = s.election_id AND p.unit_id = s.unit_id
       LEFT JOIN ${V}.lgas l ON l.election_id = s.election_id AND l.lga_id = s.lga_id
       LEFT JOIN ${V}.wards w ON w.election_id = s.election_id AND w.ward_id = s.ward_id
      WHERE s.election_id = $1 AND s.pu_code LIKE $3
      GROUP BY 1
      ORDER BY 1`,
    [electionId, width, `${under}%`, heldOn]
  );
}

/** What a place is called, from any one polling unit under it. */
export async function placeName(db, electionId, under) {
  const [row] = await db(
    `SELECT l.name AS lga_name, w.name AS ward_name
       FROM ${V}.sheets s
       LEFT JOIN ${V}.lgas l ON l.election_id = s.election_id AND l.lga_id = s.lga_id
       LEFT JOIN ${V}.wards w ON w.election_id = s.election_id AND w.ward_id = s.ward_id
      WHERE s.election_id = $1 AND s.pu_code LIKE $2
      LIMIT 1`,
    [electionId, `${under}%`]
  );
  return row ?? null;
}

/**
 * How many sheets under a place went up on each day, counted from polling
 * day: 0 is the day itself, 1 the day after. Only sheets whose file carries
 * the time; see `uploadedAt` in ./shape.js.
 */
export async function uploadDays(db, electionId, under, heldOn) {
  if (!heldOn) return [];
  return db(
    `SELECT ${daysAfter("$3")} AS day, count(*)::int AS sheets
       FROM ${V}.sheets s
      WHERE s.election_id = $1 AND s.pu_code LIKE $2 AND s.uploaded_at IS NOT NULL
      GROUP BY 1
      ORDER BY 1`,
    [electionId, `${under}%`, heldOn]
  );
}

/** Every party's votes under one place, grouped one step down, from sound readings only. */
export async function placeVotes(db, electionId, under, width) {
  return db(
    `SELECT left(r.pu_code, $2) AS key, v.key AS party, sum(v.value::int)::int AS votes
       FROM ${V}.readings r, jsonb_each_text(r.party_votes) v
      WHERE r.election_id = $1 AND r.pu_code LIKE $3 AND ${SOUND}
        AND v.value ~ '^[0-9]+$'
      GROUP BY 1, 2`,
    [electionId, width, `${under}%`]
  );
}

/**
 * The polling units under one place that carry a fault, with what it is.
 *
 * `kind` is one fault from FAULTS, or "any" for every one of them. Without
 * it the list is the grave ones only — a paper that is wrong, figures that
 * cannot be, a sheet replaced or gone — and not the tens of thousands that
 * are merely missing or late, which would bury them. The gravest first, and
 * no more than `limit`: this is a list for a person to work down.
 */
export async function placeFlags(db, electionId, under, { kind = null, heldOn = null, limit = 60 } = {}) {
  const names = FAULTS[kind] ? [kind] : kind === "any" ? FAULT_NAMES : GRAVE;
  const which = names.map((name) => FAULTS[name]("$3")).join("\n             OR ");
  return db(
    `SELECT s.unit_id, s.pu_code, s.unit_name, s.earlier_sheets, s.uploaded_at, s.no_voters,
            (s.sheet_url IS NOT NULL) AS sheet_up, ${daysAfter("$3")} AS days_after,
            ${NO_FILE} AS no_file,
            l.name AS lga_name, l.state_name, w.name AS ward_name,
            p.status AS picture_status, p.place_ok, p.days_from_poll, p.taken_lga, p.taken_state,
            r.status AS read_status, r.balanced, r.problems,
            r.code_matches, r.code_on_sheet, r.accredited, r.valid_votes, r.registered,
            (${SOUND}) AS sound
       FROM ${V}.sheets s
       LEFT JOIN ${V}.readings r ON r.election_id = s.election_id AND r.unit_id = s.unit_id
       LEFT JOIN ${V}.pictures p ON p.election_id = s.election_id AND p.unit_id = s.unit_id
       LEFT JOIN ${V}.lgas l ON l.election_id = s.election_id AND l.lga_id = s.lga_id
       LEFT JOIN ${V}.wards w ON w.election_id = s.election_id AND w.ward_id = s.ward_id
      WHERE s.election_id = $1 AND s.pu_code LIKE $2
        AND (${which})
      ORDER BY (p.place_ok IS FALSE) DESC, (r.code_matches IS FALSE) DESC,
               ${FAULTS.overvote()} DESC NULLS LAST, s.earlier_sheets DESC,
               ${FAULTS.gone()} DESC NULLS LAST,
               ${daysAfter("$3")} DESC NULLS LAST, s.pu_code
      LIMIT $4`,
    [electionId, `${under}%`, heldOn, limit]
  );
}

/** What is held for the polling units named, for holding against our own returns of them. */
export async function unitsByCode(db, electionId, codes) {
  if (!codes.length) return [];
  return db(
    `SELECT s.unit_id, s.pu_code, s.unit_name, (s.sheet_url IS NOT NULL) AS sheet_up,
            r.status, r.balanced, r.code_matches, r.registered, r.accredited, r.rejected, r.party_votes
       FROM ${V}.sheets s
       LEFT JOIN ${V}.readings r ON r.election_id = s.election_id AND r.unit_id = s.unit_id
      WHERE s.election_id = $1 AND s.pu_code = ANY($2::text[])`,
    [electionId, codes]
  );
}

/** The figures read for an election, for holding against our own returns. */
export async function readings(db, electionId) {
  return db(
    `SELECT unit_id, pu_code, status, balanced, code_matches, registered, accredited, rejected, party_votes
       FROM ${V}.readings WHERE election_id = $1 AND status = 'read'`,
    [electionId]
  );
}

export async function linkProject(db, electionId, projectId) {
  await db(`UPDATE ${V}.elections SET project_id = $2 WHERE election_id = $1`, [electionId, projectId]);
}

/** The gathered election a Poll360 project is compared with, if one was chosen. */
export async function electionForProject(db, projectId) {
  const [row] = await db(
    `SELECT e.*, to_char(e.held_on, 'YYYY-MM-DD') AS held_on
       FROM ${V}.elections e WHERE e.project_id = $1 ORDER BY e.held_on DESC LIMIT 1`,
    [projectId]
  );
  return row ?? null;
}

/**
 * Bring Data Bank's own figures up to date: the row count it shows for each
 * table, and what the source has paid in.
 */
export async function settle(db) {
  for (const table of Object.keys(TABLES)) {
    await db(
      `UPDATE dumpsite.datasets SET rows = (SELECT count(*) FROM ${V}.${table})
        WHERE table_schema = $1 AND table_name = $2`,
      [V, table]
    );
  }
  await db(
    `UPDATE dumpsite.connections
        SET last_sync_at = now(), status = 'LINKED', last_error = NULL,
            records = (SELECT count(*) FROM ${V}.sheets)
      WHERE name = 'INEC IReV'
        AND project_id = (SELECT id FROM dumpsite.projects WHERE tenant_id = 'default' AND slug = $1)`,
    [ACCOUNT.slug]
  );
}

/** How much room the account is taking. */
export async function weight(db) {
  const [row] = await db(
    `SELECT coalesce(sum(pg_total_relation_size(c.oid)), 0)::bigint AS bytes
       FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = $1 AND c.relkind = 'r'`,
    [V]
  );
  return Number(row?.bytes ?? 0);
}
