/**
 * The room's two alarms.
 *
 * ══════════════════════════════════════════════════════════════════════════
 *  WHY TWO, AND WHY THEY MUST NOT SOUND ALIKE
 *
 *  This room is told two completely different kinds of thing.
 *
 *    ATTENTION   the product noticed something. A threshold was crossed: the
 *                count has stalled, a state has gone quiet, a queue is
 *                backing up. Nobody is in danger. Somebody should look at a
 *                screen in the next few minutes.
 *
 *    SITUATION   a person standing in a field filed a report. An agent is
 *                being obstructed, a booth was closed early, there is a crowd.
 *                A human being is telling you something is wrong where they
 *                are standing, and the response is a telephone call, not a
 *                screen.
 *
 *  One sound for both means the room cannot tell, without looking, whether to
 *  walk to a monitor or pick up a phone. At two in the morning, on a wall
 *  display nobody is watching, that distinction is the entire value of having
 *  a sound at all.
 * ══════════════════════════════════════════════════════════════════════════
 *
 * ── WHY THESE ARE ALARMS AND NOT NOTIFICATION BEEPS ────────────────────────
 * The first version of this file played two pure tones with a soft rise and a
 * soft fall. It was polite, and polite is the one thing an alarm must never
 * be: it sat under the air conditioning, it sounded like a phone in somebody
 * else's pocket, and across a room with four people talking it was not there
 * at all. A sound a room has to strain to hear is a sound the room stops
 * relying on, and then the screen is back to being a red dot nobody sees.
 *
 * So both voices are built out of the four things that make a noise read as
 * an alarm rather than as a notification:
 *
 *   HARMONICS   a stack of detuned oscillators rather than one clean tone.
 *               A pure sine is a flute and is masked by conversation; a stack
 *               with its harmonics is a sounder and cuts through it.
 *   A FILTER    swept across the note, which is what gives a sounder its body
 *               and stops a stack sounding like a synthesiser.
 *   AN ENVELOPE that snaps on, holds flat, and cuts. A tone that fades in and
 *               out is a doorbell. A tone that holds is an alarm.
 *   MOVEMENT    a figure that goes somewhere and then comes back, several
 *               times over. A sound that sits still becomes part of the room
 *               within about four seconds.
 *
 * ── AND THE FIFTH THING, WHICH IS A TRAP ───────────────────────────────────
 * Drive — a soft clip, the distortion of a cheap horn driver pushed hard. It
 * is the obvious way to make a sound aggressive and it is mostly a mistake.
 * The situation voice was built that way first, as an emergency horn: a
 * sawtooth stack over a sub-octave, heavily clipped, with a nine-per-second
 * wobble. Everything about it was urgent on paper and it was simply unpleasant
 * to listen to — muddy rather than alarming, the sound of equipment breaking
 * rather than of equipment working. It was rejected on hearing, which is the
 * only way a sound can be judged.
 *
 * So the situation voice is now the cleanest thing in this file and carries on
 * its figure instead. Drive survives only on the attention voice, lightly, and
 * anything added here should be listened to before it is believed.
 *
 * ── HOW THEY ARE TOLD APART, ON FIVE AXES AT ONCE ──────────────────────────
 * Two alarms that differ only in pitch are two alarms a tired person confuses
 * within a week. These differ on everything a listener can use:
 *
 *                    ATTENTION                 SITUATION
 *   direction        rising, and stays up      an arch, up and back down
 *   register         high (1244→2093 Hz)       low (587→784 Hz)
 *   figure           two notes                 five
 *   timbre           driven, thin, hard        clean, round, undistorted
 *   rhythm           quick, even, mechanical   measured, melodic, deliberate
 *
 * Rising, bright and mechanical is a panel telling you a number moved. The
 * five-note arch is the shape a hospital monitor uses for its high-priority
 * alarm, and it is the shape it uses because it has to be heard all night by
 * people who must not be worn down by it — which is this room exactly. That
 * is not decoration: a room should not have to be trained, and should not
 * have to look.
 *
 * ── AND WHY THE SYNTHESIS IS HERE RATHER THAN IN A FILE ────────────────────
 * No audio assets. A room may be on a venue's wifi at nine at night behind a
 * proxy that has never heard of this product, and an alarm that depends on a
 * file finishing a download is an alarm that is silent exactly when the
 * network is bad — which correlates alarmingly well with when the night is
 * going badly. Everything below is generated by the browser's own oscillators
 * and cannot fail to load.
 */

/* --------------------------------------------------------------- the voices */

/**
 * The two voices, and the severities within each.
 *
 * The timbre fields are the voice: they are what a listener recognises, and
 * they never change between severities, because a louder version of the same
 * alarm is still recognisably that alarm. The `levels` are the figure played
 * in that voice — the notes as [frequency, seconds], how many times over, and
 * how loud.
 *
 *   partials  the oscillator stack, as [ratio of the fundamental, gain]. A
 *             ratio below 1 is a sub-octave, which is body rather than pitch.
 *   detune    cents of spread between the stack's two halves. A few cents of
 *             disagreement is what stops a stack sounding like a synthesiser.
 *   filter    a resonant sweep, as [type, from Hz, to Hz, Q]. The sweep runs
 *             across each note.
 *   drive     0 to 1, how hard the soft clip bites. 0 is no distortion at
 *             all, which is what a clean sounder wants; see the trap above.
 *   tremolo   [rate Hz, depth 0-1], the pulse. Depth 0.6 means the sound
 *             swings between 40% and 100% of its loudness, rate times a
 *             second.
 *   warble    cents of pitch wobble, several times a second. Kept as a plain
 *             number because it is also the flag for "this voice moves".
 *   glide     how much of a note is spent sliding into the pitch of the next
 *             one, as a fraction. 0 is a stepped two-tone, which is a
 *             doorbell. A third is a siren. A whole 1 never settles on a
 *             pitch at all, which is the wail of an air-raid siren.
 */
export const VOICES = {
  ATTENTION: {
    id: "ATTENTION",
    label: "Attention",
    what: "The product noticed something. Look at a screen.",

    /* A fire-panel sounder. Square, bright, mechanical, with just enough
       drive to buzz. It is meant to be unmistakably an alarm and still be
       something a room can hear four times an hour without wearing out. */
    wave: "square",
    partials: [[1, 1], [2, 0.4], [3, 0.22], [4, 0.1]],
    detune: 5,
    filter: ["bandpass", 2400, 3200, 1.1],
    drive: 0.3,
    tremolo: null,
    warble: 0,
    glide: 0,

    levels: {
      /* One pulse. A threshold worth knowing about and nothing more. */
      INFO: { steps: [[1244.5, 0.1], [1661.2, 0.13]], gap: 0.06, repeat: 1, volume: 0.24 },
      WARNING: { steps: [[1244.5, 0.1], [1661.2, 0.13]], gap: 0.06, repeat: 2, volume: 0.34 },
      /* Three, which is the pattern every fire panel in the world uses for
         "this is real", and which a room reads as urgent without instruction. */
      SERIOUS: { steps: [[1244.5, 0.1], [1864.7, 0.14]], gap: 0.06, repeat: 3, volume: 0.44 },
      CRITICAL: { steps: [[1396.9, 0.1], [2093, 0.16]], gap: 0.06, repeat: 4, volume: 0.56 },
    },
  },

  SITUATION: {
    id: "SITUATION",
    label: "Situation",
    what: "Somebody in a field filed a report. Ring them.",

    /* A monitor alarm. Square, but barely driven and gently filtered, so what
       carries is the figure rather than any harshness in the tone. It is the
       cleanest sound in this product on purpose: this is the alarm most likely
       to go off repeatedly through a long night, and an abrasive one is an
       alarm somebody eventually mutes. See the trap, above. */
    wave: "square",
    partials: [[1, 1], [2, 0.3], [3, 0.12]],
    detune: 2,
    filter: ["lowpass", 3200, 2800, 1],
    drive: 0,
    tremolo: null,
    warble: 0,
    glide: 0,

    levels: {
      /* Three notes, once. A report has come in and it is not an emergency. */
      INFO: { steps: [[587.3, 0.11], [659.3, 0.11], [784, 0.18]], gap: 0.05, repeat: 1, volume: 0.3 },
      WARNING: { steps: [[587.3, 0.11], [659.3, 0.11], [784, 0.18]], gap: 0.05, repeat: 2, volume: 0.42 },
      /* Five: up and back down. The arch is the thing a listener recognises,
         and it is what separates the serious half of this lane from the
         ordinary half without anybody having to count pulses. */
      SERIOUS: {
        steps: [[587.3, 0.11], [659.3, 0.11], [784, 0.11], [659.3, 0.11], [587.3, 0.18]],
        gap: 0.05,
        repeat: 2,
        volume: 0.55,
      },
      /* The arch three times over, at full volume. Nothing else in this
         product makes this noise, and it means one thing. */
      CRITICAL: {
        steps: [[587.3, 0.11], [659.3, 0.11], [784, 0.11], [659.3, 0.11], [587.3, 0.18]],
        gap: 0.05,
        repeat: 3,
        volume: 0.68,
      },
    },
  },
};

export const VOICE_ORDER = ["SITUATION", "ATTENTION"];

/** Loudest first. The order a batch is reduced to one sounding. */
export const SEVERITY_RANK = { CRITICAL: 4, SERIOUS: 3, WARNING: 2, INFO: 1 };

/** How long the whole figure lasts, so a caller can schedule around it. */
export function durationOf(voiceId, level) {
  const voice = VOICES[voiceId];
  const pattern = voice?.levels[level] ?? voice?.levels.INFO;
  if (!pattern) return 0;
  const once = pattern.steps.reduce((sum, [, length]) => sum + length + pattern.gap, 0);
  return once * pattern.repeat + pattern.gap * (pattern.repeat - 1);
}

/* ------------------------------------------------------------ what is new */

/**
 * What has arrived since the last look, and how loud it should be.
 *
 * ══════════════════════════════════════════════════════════════════════════
 *  THE ONE PIECE OF LOGIC AN ALARM CANNOT GET WRONG
 *
 *  Two failures, opposite and both fatal to the feature:
 *
 *    Sounding for something already announced. The room hears the same alarm
 *    every fifteen seconds for a report from an hour ago, and within twenty
 *    minutes somebody mutes the tab — and then the one at 02:40 is silent.
 *
 *    Sounding for the backlog on arrival. Somebody opens the dashboard at 9pm
 *    and is met by forty alarms for things that happened before they sat
 *    down. Same outcome, faster.
 *
 *  So `seen` being null means "this is the first look" and nothing sounds.
 *  Everything already on the page at that moment is history by definition.
 *  It is a pure function, and it is a pure function because a room's trust in
 *  its own alarm has to be checkable by a test rather than by waiting until
 *  two in the morning to find out.
 * ══════════════════════════════════════════════════════════════════════════
 *
 * @param rows  whatever is on the page now: [{ id, level | severity }]
 * @param seen  the ids already announced, or null on the very first look
 * @returns { fresh, level, seen } — `seen` is the set to hold for next time
 */
export function newArrivals(rows = [], seen = null) {
  const ids = new Set(rows.map((row) => row.id).filter((id) => id !== undefined && id !== null));

  /* First look. Everything here is backlog, and backlog is silent. */
  if (seen === null) return { fresh: [], level: null, seen: ids, first: true };

  const fresh = rows.filter((row) => row.id !== undefined && row.id !== null && !seen.has(row.id));

  /* The set carried forward is what is on the page now, plus what was already
     seen. Not just the current page: a row that scrolls off the end of a
     capped feed and comes back must not sound a second time. */
  const next = new Set(seen);
  for (const id of ids) next.add(id);

  if (!fresh.length) return { fresh: [], level: null, seen: next, first: false };

  /* The worst in the batch sets the tone. Two arriving together should sound
     like the more serious of the two, never like two of the milder one. */
  const level = fresh.reduce((worst, row) => {
    const found = row.level ?? row.severity ?? "INFO";
    return (SEVERITY_RANK[found] ?? 0) > (SEVERITY_RANK[worst] ?? 0) ? found : worst;
  }, "INFO");

  return { fresh, level, seen: next, first: false };
}

/**
 * Which rows an alarm is allowed to sound for.
 *
 * "Normal" is a row in the alert list and it says everything is fine. Sounding
 * an alarm for it would be the single fastest way to destroy the feature, so
 * it is filtered here rather than in each of the three callers that would each
 * have to remember.
 */
export function soundable(rows = []) {
  return rows.filter((row) => (row.level ?? row.severity ?? "INFO") !== "NORMAL");
}

/* ------------------------------------------------------------- the speaker */

/** The snap on and the cut off, in seconds. Short, because a slow edge is a
    doorbell and a hard one is an alarm — but not zero, because a true square
    edge is a click, and a click on a cheap wall speaker sounds like a fault
    in the equipment rather than like an alarm. */
const ATTACK = 0.006;
const RELEASE = 0.018;

/**
 * The soft clip.
 *
 * This is the buzz, and the buzz is most of what the ear files under "alarm".
 * A real sounder distorts because it is a cheap driver pushed hard; this is
 * the same curve, on purpose. It is built once per amount and kept, because
 * filling a thousand-point array on every note of every alarm all night is
 * work nobody needs done twice.
 */
const curves = new Map();
function clipCurve(amount) {
  const key = Math.round(amount * 100);
  const held = curves.get(key);
  if (held) return held;

  const points = 1024;
  const curve = new Float32Array(points);
  const k = amount * 60;
  for (let i = 0; i < points; i += 1) {
    const x = (i * 2) / points - 1;
    curve[i] = ((1 + k) * x) / (1 + k * Math.abs(x));
  }
  curves.set(key, curve);
  return curve;
}

/**
 * The thing that actually makes a noise.
 *
 * Created once per page and handed the browser's AudioContext lazily, because
 * constructing one before a user gesture is what browsers refuse. Everything
 * that can fail — no Web Audio at all, a context the browser will not resume —
 * fails to silence rather than to an exception: an alarm that throws takes the
 * screen down with it, and a screen that is down cannot show the thing the
 * alarm was about.
 */
export function createSpeaker() {
  let context = null;
  let master = null;
  let blocked = false;

  const ctx = () => {
    if (typeof window === "undefined") return null;
    const Ctor = window.AudioContext ?? window.webkitAudioContext;
    if (!Ctor) return null;
    if (!context) {
      try {
        context = new Ctor();
      } catch {
        return null;
      }
    }
    return context;
  };

  /**
   * The output stage, built once.
   *
   * ── WHY THERE IS A COMPRESSOR ON THE END ──────────────────────────────
   * These voices are loud on purpose, they stack several oscillators, and two
   * lanes can fire within the same second. Summed straight into the output
   * that clips, and digital clipping is a crackle — which a room hears as a
   * broken speaker, not as an alarm. The compressor holds the ceiling so the
   * alarm can be as loud as it needs to be and still sound like equipment
   * that works.
   */
  const out = (audio) => {
    if (master) return master;
    const limiter = audio.createDynamicsCompressor();
    limiter.threshold.setValueAtTime(-8, audio.currentTime);
    limiter.knee.setValueAtTime(3, audio.currentTime);
    limiter.ratio.setValueAtTime(12, audio.currentTime);
    limiter.attack.setValueAtTime(0.002, audio.currentTime);
    limiter.release.setValueAtTime(0.12, audio.currentTime);
    limiter.connect(audio.destination);
    master = limiter;
    return master;
  };

  /**
   * Arm the context on a real gesture, which is what the autoplay policy
   * wants. Returns whether the browser is still holding us, so a screen can
   * say so in words rather than being silently mute.
   */
  const arm = async () => {
    const audio = ctx();
    if (!audio) return false;
    if (audio.state === "running") {
      blocked = false;
      return true;
    }
    try {
      await audio.resume();
    } catch {
      /* No gesture yet. Not an error; the caller is told. */
    }
    blocked = audio.state !== "running";
    return !blocked;
  };

  /**
   * One note of one voice, with its whole chain.
   *
   *   oscillator stack → drive → resonant filter → tremolo → envelope → out
   *
   * Everything is scheduled ahead on the audio clock and torn down by its own
   * stop time, so a figure is fully described the moment it starts and does
   * not depend on the main thread staying free — which matters, because the
   * main thread is busy rendering the dashboard that just changed.
   */
  const note = (audio, voice, { frequency, glideTo, length, at, volume }) => {
    const ends = at + length;

    /* The envelope. Snap on, hold flat, cut. The hold is the whole point:
       a tone that starts fading the moment it arrives is a notification. */
    const env = audio.createGain();
    const peak = Math.max(0.0001, volume);
    const release = Math.min(RELEASE, length / 3);
    env.gain.setValueAtTime(0, at);
    env.gain.linearRampToValueAtTime(peak, at + Math.min(ATTACK, length / 4));
    env.gain.setValueAtTime(peak, ends - release);
    env.gain.linearRampToValueAtTime(0, ends);
    env.connect(out(audio));

    /* The tremolo: a pulse in the loudness, not the pitch. It is what turns
       a held horn into a yelp, and a yelp is heard across a room that a
       steady tone disappears into within about four seconds. */
    let head = env;
    if (voice.tremolo) {
      const [rate, depth] = voice.tremolo;
      const pulse = audio.createGain();
      pulse.gain.setValueAtTime(1 - depth / 2, at);

      const lfo = audio.createOscillator();
      const swing = audio.createGain();
      lfo.type = "sine";
      lfo.frequency.setValueAtTime(rate, at);
      swing.gain.setValueAtTime(depth / 2, at);
      lfo.connect(swing).connect(pulse.gain);
      lfo.start(at);
      lfo.stop(ends + 0.02);

      pulse.connect(env);
      head = pulse;
    }

    /* The filter, swept across the note. This is the throat of the sound:
       the same oscillators through a flat filter are a synthesiser, and
       through this are a horn. */
    const [type, from, to, q] = voice.filter;
    const shape = audio.createBiquadFilter();
    shape.type = type;
    shape.Q.setValueAtTime(q, at);
    shape.frequency.setValueAtTime(from, at);
    shape.frequency.linearRampToValueAtTime(to, ends);
    shape.connect(head);

    /* The drive. Fed at a level that actually reaches the bend in the curve,
       then brought back down, because a soft clip driven gently does nothing
       at all and is worse than not having one. */
    const into = audio.createGain();
    const clip = audio.createWaveShaper();
    clip.curve = clipCurve(voice.drive);
    clip.oversample = "2x";
    into.gain.setValueAtTime(0.8 + voice.drive * 1.6, at);
    into.connect(clip).connect(shape);

    /* The stack. Each partial is its own oscillator, and the halves of the
       stack are pulled a few cents apart so they beat against each other
       rather than sounding like one machine-perfect tone. */
    const stacked = voice.partials.reduce((sum, [, gain]) => sum + gain, 0) || 1;

    voice.partials.forEach(([ratio, gain], index) => {
      const oscillator = audio.createOscillator();
      const level = audio.createGain();

      oscillator.type = voice.wave;
      oscillator.detune.setValueAtTime(index % 2 ? voice.detune : -voice.detune, at);
      oscillator.frequency.setValueAtTime(frequency * ratio, at);

      /* The glide, as a fraction of the note spent sliding into the next
         pitch. 0 is a stepped two-tone, which is a doorbell. A third is a
         siren that still lets you hear the note it left. A whole 1 never
         holds a pitch at all, which is the wail of an air-raid siren. */
      if (voice.glide > 0 && glideTo) {
        const slide = Math.min(1, voice.glide) * length;
        oscillator.frequency.setValueAtTime(frequency * ratio, ends - slide);
        oscillator.frequency.linearRampToValueAtTime(glideTo * ratio, ends);
      }

      /* The warble: a second oscillator bending the first one's pitch a few
         cents either side, several times a second. Small, because the tremolo
         is doing the loud work — this only stops the note sitting still. */
      if (voice.warble) {
        const wobble = audio.createOscillator();
        const depth = audio.createGain();
        wobble.type = "sine";
        wobble.frequency.setValueAtTime(voice.warble, at);
        depth.gain.setValueAtTime(frequency * ratio * 0.02, at);
        wobble.connect(depth).connect(oscillator.frequency);
        wobble.start(at);
        wobble.stop(ends + 0.02);
      }

      level.gain.setValueAtTime(gain / stacked, at);
      oscillator.connect(level).connect(into);
      oscillator.start(at);
      oscillator.stop(ends + 0.02);
    });
  };

  /**
   * Play one figure of one voice.
   */
  const play = async (voiceId, level = "INFO") => {
    /* A voice by name, or a whole voice passed in. The second form is how a
       candidate is auditioned against the shipped ones without four rejected
       alarms having to live in the table first. */
    const voice = typeof voiceId === "string" ? VOICES[voiceId] : voiceId;
    if (!voice?.levels) return false;

    const audio = ctx();
    if (!audio) return false;

    /* ── resume() IS ASYNCHRONOUS ──────────────────────────────────────
       Reading `state` on the line after calling resume() reads the old
       value — still "suspended" — so a guard written that way refuses to
       play every single time, and the alarm never sounds once. */
    if (audio.state !== "running") {
      const ready = await arm();
      if (!ready) return false;
    }
    blocked = false;

    const pattern = voice.levels[level] ?? voice.levels.INFO;
    let at = audio.currentTime + 0.02;

    try {
      for (let round = 0; round < pattern.repeat; round += 1) {
        pattern.steps.forEach(([frequency, length], index) => {
          const next = pattern.steps[index + 1] ?? (round + 1 < pattern.repeat ? pattern.steps[0] : null);
          note(audio, voice, {
            frequency,
            glideTo: next?.[0] ?? null,
            length,
            at,
            volume: pattern.volume,
          });
          at += length + pattern.gap;
        });
        at += pattern.gap;
      }
    } catch {
      /* A context that died between the guard and the schedule. Silence is
         the right failure: the screen this alarm belongs to must survive it. */
      return false;
    }

    return true;
  };

  return {
    play,
    arm,
    isBlocked: () => blocked,
    close: () => {
      try {
        context?.close();
      } catch {
        /* Already closed, or never opened. Nothing to do. */
      }
      context = null;
      master = null;
    },
  };
}
