/**
 * The room's two alarms.
 *
 * ══════════════════════════════════════════════════════════════════════════
 *  WHY TWO, AND WHY THEY MUST NOT SOUND ALIKE
 *
 *  This room is told two completely different kinds of thing, and until now
 *  both made the same noise.
 *
 *    ATTENTION   the product noticed something. A threshold was crossed: the
 *                count has stalled, a state has gone quiet, a queue is
 *                backing up. Nobody is in danger. Somebody should look at a
 *                screen in the next few minutes.
 *
 *    SITUATION   a person standing in a field filed a report. An agent is
 *                being obstructed, a booth was closed early, there is a crowd.
 *                A human being is telling you something is wrong where they
 *                are standing, and the response is a telephone call, not a
 *                screen.
 *
 *  One sound for both means the room cannot tell, without looking, whether to
 *  walk to a monitor or pick up a phone. At two in the morning, on a wall
 *  display nobody is watching, that distinction is the entire value of having
 *  a sound at all.
 * ══════════════════════════════════════════════════════════════════════════
 *
 * ── HOW THEY ARE TOLD APART, ON FOUR AXES AT ONCE ──────────────────────────
 * Two alarms that differ only in pitch are two alarms a tired person confuses
 * within a week. These differ on everything a listener can use:
 *
 *                    ATTENTION              SITUATION
 *   direction        rising                 falling
 *   register         high (1046→1568 Hz)    low (392→262 Hz)
 *   pulses           two                    three
 *   timbre           clean sine             sawtooth with a slow warble
 *   rhythm           quick, even            slower, insistent
 *
 * Rising-and-bright is the shape every notification sound on earth already
 * uses, and it reads as information. Falling-and-rough with a warble is the
 * shape of a klaxon, and it reads as trouble. That is not decoration: a room
 * should not have to be trained, and it should not have to look.
 *
 * ── AND WHY THE SYNTHESIS IS HERE RATHER THAN IN A FILE ────────────────────
 * No audio assets. A room may be on a venue's wifi at nine at night behind a
 * proxy that has never heard of this product, and an alarm that depends on a
 * file finishing a download is an alarm that is silent exactly when the
 * network is bad — which correlates alarmingly well with when the night is
 * going badly. Everything below is generated by the browser's own oscillators
 * and cannot fail to load.
 */

/* --------------------------------------------------------------- the voices */

/**
 * The two voices, and the severities within each.
 *
 * `steps` are the notes, in order, as [frequency, seconds]. `repeat` is how
 * many times the whole figure plays. Loudness rises with severity and nothing
 * else does — a louder version of the same shape is still recognisably the
 * same alarm, which is the point.
 */
export const VOICES = {
  ATTENTION: {
    id: "ATTENTION",
    label: "Attention",
    what: "The product noticed something. Look at a screen.",
    /* Clean, so it sits under conversation rather than cutting through it. */
    wave: "sine",
    warble: 0,
    levels: {
      /* A threshold worth knowing about and nothing more. */
      INFO: { steps: [[1046.5, 0.07], [1318.5, 0.09]], gap: 0.05, repeat: 1, volume: 0.1 },
      WARNING: { steps: [[1046.5, 0.07], [1318.5, 0.1]], gap: 0.05, repeat: 1, volume: 0.16 },
      /* Twice, because a serious threshold should not be mistakeable for the
         ordinary one when somebody is half listening. */
      SERIOUS: { steps: [[1046.5, 0.07], [1568, 0.11]], gap: 0.05, repeat: 2, volume: 0.22 },
      CRITICAL: { steps: [[1046.5, 0.07], [1568, 0.12]], gap: 0.05, repeat: 3, volume: 0.28 },
    },
  },

  SITUATION: {
    id: "SITUATION",
    label: "Situation",
    what: "Somebody in a field filed a report. Ring them.",
    /* Rough and low. A sawtooth carries across a room and through a door in a
       way a sine does not, which is the difference between a report being
       seen at once and being seen at the end of a phone call. */
    wave: "sawtooth",
    /* A slow wobble on the pitch. It is what makes this read as an alarm
       rather than as a low beep, and it is the single most recognisable thing
       about it from the far side of a room. */
    warble: 7,
    levels: {
      INFO: { steps: [[392, 0.14], [329.6, 0.16]], gap: 0.07, repeat: 1, volume: 0.12 },
      WARNING: { steps: [[392, 0.14], [329.6, 0.18]], gap: 0.07, repeat: 1, volume: 0.18 },
      SERIOUS: { steps: [[440, 0.14], [349.2, 0.14], [293.7, 0.2]], gap: 0.07, repeat: 1, volume: 0.26 },
      /* Three falling notes, three times over. Nothing else in this product
         makes this noise, and it means one thing. */
      CRITICAL: { steps: [[440, 0.14], [349.2, 0.14], [261.6, 0.24]], gap: 0.07, repeat: 3, volume: 0.34 },
    },
  },
};

export const VOICE_ORDER = ["SITUATION", "ATTENTION"];

/** Loudest first. The order a batch is reduced to one sounding. */
export const SEVERITY_RANK = { CRITICAL: 4, SERIOUS: 3, WARNING: 2, INFO: 1 };

/** How long the whole figure lasts, so a caller can schedule around it. */
export function durationOf(voiceId, level) {
  const voice = VOICES[voiceId];
  const pattern = voice?.levels[level] ?? voice?.levels.INFO;
  if (!pattern) return 0;
  const once = pattern.steps.reduce((sum, [, length]) => sum + length + pattern.gap, 0);
  return once * pattern.repeat + pattern.gap * (pattern.repeat - 1);
}

/* ------------------------------------------------------------ what is new */

/**
 * What has arrived since the last look, and how loud it should be.
 *
 * ══════════════════════════════════════════════════════════════════════════
 *  THE ONE PIECE OF LOGIC AN ALARM CANNOT GET WRONG
 *
 *  Two failures, opposite and both fatal to the feature:
 *
 *    Sounding for something already announced. The room hears the same alarm
 *    every fifteen seconds for a report from an hour ago, and within twenty
 *    minutes somebody mutes the tab — and then the one at 02:40 is silent.
 *
 *    Sounding for the backlog on arrival. Somebody opens the dashboard at 9pm
 *    and is met by forty alarms for things that happened before they sat
 *    down. Same outcome, faster.
 *
 *  So `seen` being null means "this is the first look" and nothing sounds.
 *  Everything already on the page at that moment is history by definition.
 *  It is a pure function, and it is a pure function because a room's trust in
 *  its own alarm has to be checkable by a test rather than by waiting until
 *  two in the morning to find out.
 * ══════════════════════════════════════════════════════════════════════════
 *
 * @param rows  whatever is on the page now: [{ id, level | severity }]
 * @param seen  the ids already announced, or null on the very first look
 * @returns { fresh, level, seen } — `seen` is the set to hold for next time
 */
export function newArrivals(rows = [], seen = null) {
  const ids = new Set(rows.map((row) => row.id).filter((id) => id !== undefined && id !== null));

  /* First look. Everything here is backlog, and backlog is silent. */
  if (seen === null) return { fresh: [], level: null, seen: ids, first: true };

  const fresh = rows.filter((row) => row.id !== undefined && row.id !== null && !seen.has(row.id));

  /* The set carried forward is what is on the page now, plus what was already
     seen. Not just the current page: a row that scrolls off the end of a
     capped feed and comes back must not sound a second time. */
  const next = new Set(seen);
  for (const id of ids) next.add(id);

  if (!fresh.length) return { fresh: [], level: null, seen: next, first: false };

  /* The worst in the batch sets the tone. Two arriving together should sound
     like the more serious of the two, never like two of the milder one. */
  const level = fresh.reduce((worst, row) => {
    const found = row.level ?? row.severity ?? "INFO";
    return (SEVERITY_RANK[found] ?? 0) > (SEVERITY_RANK[worst] ?? 0) ? found : worst;
  }, "INFO");

  return { fresh, level, seen: next, first: false };
}

/**
 * Which rows an alarm is allowed to sound for.
 *
 * "Normal" is a row in the alert list and it says everything is fine. Sounding
 * an alarm for it would be the single fastest way to destroy the feature, so
 * it is filtered here rather than in each of the three callers that would each
 * have to remember.
 */
export function soundable(rows = []) {
  return rows.filter((row) => (row.level ?? row.severity ?? "INFO") !== "NORMAL");
}

/* ------------------------------------------------------------- the speaker */

/**
 * The thing that actually makes a noise.
 *
 * Created once per page and handed the browser's AudioContext lazily, because
 * constructing one before a user gesture is what browsers refuse. Everything
 * that can fail — no Web Audio at all, a context the browser will not resume —
 * fails to silence rather than to an exception: an alarm that throws takes the
 * screen down with it, and a screen that is down cannot show the thing the
 * alarm was about.
 */
export function createSpeaker() {
  let context = null;
  let blocked = false;

  const ctx = () => {
    if (typeof window === "undefined") return null;
    const Ctor = window.AudioContext ?? window.webkitAudioContext;
    if (!Ctor) return null;
    if (!context) {
      try {
        context = new Ctor();
      } catch {
        return null;
      }
    }
    return context;
  };

  /**
   * Arm the context on a real gesture, which is what the autoplay policy
   * wants. Returns whether the browser is still holding us, so a screen can
   * say so in words rather than being silently mute.
   */
  const arm = async () => {
    const audio = ctx();
    if (!audio) return false;
    if (audio.state === "running") {
      blocked = false;
      return true;
    }
    try {
      await audio.resume();
    } catch {
      /* No gesture yet. Not an error; the caller is told. */
    }
    blocked = audio.state !== "running";
    return !blocked;
  };

  /**
   * Play one figure of one voice.
   *
   * Every note is ramped in and out rather than switched. A square edge on a
   * cheap wall speaker at one in the morning sounds like a fault in the
   * equipment, which is precisely the wrong thing for an alarm to sound like.
   */
  const play = async (voiceId, level = "INFO") => {
    const voice = VOICES[voiceId];
    if (!voice) return false;

    const audio = ctx();
    if (!audio) return false;

    /* ── resume() IS ASYNCHRONOUS ──────────────────────────────────────
       Reading `state` on the line after calling resume() reads the old
       value — still "suspended" — so a guard written that way refuses to
       play every single time, and the alarm never sounds once. */
    if (audio.state !== "running") {
      const ready = await arm();
      if (!ready) return false;
    }
    blocked = false;

    const pattern = voice.levels[level] ?? voice.levels.INFO;
    let at = audio.currentTime + 0.02;

    for (let round = 0; round < pattern.repeat; round += 1) {
      for (const [frequency, length] of pattern.steps) {
        const oscillator = audio.createOscillator();
        const gain = audio.createGain();

        oscillator.type = voice.wave;
        oscillator.frequency.setValueAtTime(frequency, at);

        /* The warble, which is what makes the situation alarm read as a
           klaxon rather than as a low beep. A second oscillator bending the
           first one's pitch a few hertz either side, several times a second. */
        if (voice.warble) {
          const wobble = audio.createOscillator();
          const depth = audio.createGain();
          wobble.type = "sine";
          wobble.frequency.setValueAtTime(voice.warble, at);
          depth.gain.setValueAtTime(frequency * 0.02, at);
          wobble.connect(depth).connect(oscillator.frequency);
          wobble.start(at);
          wobble.stop(at + length + 0.02);
        }

        gain.gain.setValueAtTime(0.0001, at);
        gain.gain.exponentialRampToValueAtTime(pattern.volume, at + 0.015);
        gain.gain.exponentialRampToValueAtTime(0.0001, at + length);

        oscillator.connect(gain).connect(audio.destination);
        oscillator.start(at);
        oscillator.stop(at + length + 0.02);

        at += length + pattern.gap;
      }
      at += pattern.gap;
    }

    return true;
  };

  return {
    play,
    arm,
    isBlocked: () => blocked,
    close: () => {
      try {
        context?.close();
      } catch {
        /* Already closed, or never opened. Nothing to do. */
      }
      context = null;
    },
  };
}
