import { readFileSync } from "node:fs";
import { join } from "node:path";

import { STATES } from "./units.js";
import { lgasForState, lgaNameForCode } from "./lga-names.js";
import { LEVELS } from "./territory.js";

if (typeof window !== "undefined") {
  throw new Error("lib/constituencies.js reads from disk and is server only");
}

/**
 * The places a seat is contested in.
 *
 * ── WHERE THIS TABLE COMES FROM ────────────────────────────────────────────
 * public/geo/constituencies.json is generated by
 * scripts/build-constituencies.mjs from a published dump committed beside it,
 * joined to the 774 local governments this repository already draws, and
 * refused outright unless it comes to 109 senatorial districts, 360 federal
 * constituencies and every local government accounted for exactly once. Read
 * that script for what was corrected and why; nothing is corrected here.
 *
 * ── WHY IT IS READ FROM DISK RATHER THAN IMPORTED ──────────────────────────
 * Ninety-five kilobytes, and a page needs a few hundred bytes of it: the
 * three districts in one state, or the one an account is tied to. Imported as
 * a module it would be ninety-five kilobytes in the browser bundle of every
 * screen that so much as names a district. Read here and passed down as
 * props, the browser gets what it is actually going to draw — which is the
 * same trade lib/lga-names.js makes, for the same reason.
 * ───────────────────────────────────────────────────────────────────────────
 */

let table = null;

function load() {
  if (table) return table;
  try {
    const file = join(process.cwd(), "public", "geo", "constituencies.json");
    const data = JSON.parse(readFileSync(file, "utf8"));
    table = { senatorial: data.senatorial ?? [], federal: data.federal ?? [] };
  } catch {
    /* A deployment that never ran the build has no districts. Every caller
       below returns nothing rather than something invented, and the pickers
       that read them show a state list with no districts under it — which is
       visibly broken, and is meant to be. A silent fallback to "the whole
       state" would put an account on three times the map it asked for and
       nothing would ever say so. */
    table = { senatorial: [], federal: [] };
  }
  return table;
}

const byLevel = {
  SENATORIAL: () => load().senatorial,
  FEDERAL: () => load().federal,
};

/** Every senatorial district in a state, in the order a form should offer them. */
export function senatorialIn(stateNumber) {
  return inState("SENATORIAL", stateNumber);
}

/** Every federal constituency in a state, likewise. */
export function federalIn(stateNumber) {
  return inState("FEDERAL", stateNumber);
}

function inState(level, stateNumber) {
  const wanted = String(stateNumber ?? "").padStart(2, "0");
  return (byLevel[level]?.() ?? [])
    .filter((row) => row.state === wanted)
    .sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Everything a picker needs for one state, in one read.
 *
 * ── WHY ALL FOUR AT ONCE ───────────────────────────────────────────────────
 * The form asks for a contest and then for a place, and which place list it
 * needs depends on the contest. Fetching per contest would mean the list
 * arriving after the choice that needs it — over a phone connection at a
 * campaign office, that is a dropdown that is empty at the moment somebody
 * looks at it. It is a few kilobytes for one state. It goes down with the
 * page.
 */
export function placesIn(stateNumber) {
  const wanted = String(stateNumber ?? "").padStart(2, "0");
  return {
    state: wanted,
    lgas: lgasForState(wanted),
    senatorial: senatorialIn(wanted).map(slim),
    federal: federalIn(wanted).map(slim),
  };
}

/**
 * The same for every state at once, for a form that has not been told one yet.
 *
 * Around a hundred kilobytes of names with no local government lists attached,
 * which is what `slim` is for: a picker needs to show a district and send its
 * key, and the places inside it are the server's business until somebody has
 * actually chosen one.
 */
export function allPlaces() {
  return STATES.map((state) => ({
    number: state.number,
    name: state.name,
    code: state.code,
    lgas: lgasForState(state.number),
    senatorial: senatorialIn(state.number).map(slim),
    federal: federalIn(state.number).map(slim),
  }));
}

const slim = (row) => ({ key: row.key, name: row.name, shared: row.shared ?? null });

/**
 * A stored territory, resolved into the places it actually contains.
 *
 * ── THE ONE FUNCTION EVERYTHING ELSE IS BUILT ON ───────────────────────────
 * A guard asks it whether a return belongs to a room. A map asks it which
 * shapes to draw. A coverage figure asks it for its denominator. All three
 * have to be answering about the same set of local governments or the room is
 * reading a percentage of one place against the booths of another, so all
 * three ask here.
 *
 * Returns null for a territory that names nothing we hold — a district key
 * from a table that has since been rebuilt, a local government code outside
 * its state. Null is not "everywhere": callers treat it as a territory that
 * could not be resolved and say so, because an account silently promoted to
 * the whole federation is the failure this module exists to prevent.
 */
export function resolveTerritory(descriptor) {
  const parsed = typeof descriptor === "string" ? parse(descriptor) : descriptor;
  if (!parsed?.level) return null;

  const { level, key } = parsed;

  if (level === "NATION") {
    return { level, key: null, name: "Nigeria", stateNumber: null, stateName: null, stateCode: null, lgas: null };
  }

  if (level === "STATE") {
    const state = STATES.find((row) => row.number === String(key).padStart(2, "0"));
    if (!state) return null;
    return {
      level,
      key: state.number,
      name: state.name,
      stateNumber: state.number,
      stateName: state.name,
      stateCode: state.code,
      lgas: lgasForState(state.number).map((row) => row.code),
    };
  }

  if (level === "LGA") {
    const [stateNumber] = String(key).split("/");
    const state = STATES.find((row) => row.number === String(stateNumber).padStart(2, "0"));
    const name = lgaNameForCode(key);
    if (!state || !name) return null;
    return {
      level,
      key,
      name,
      stateNumber: state.number,
      stateName: state.name,
      stateCode: state.code,
      lgas: [key],
    };
  }

  const row = (byLevel[level]?.() ?? []).find((one) => one.key === key);
  if (!row) return null;

  return {
    level,
    key: row.key,
    name: row.name,
    stateNumber: row.state,
    stateName: row.stateName,
    stateCode: row.stateCode,
    lgas: row.lgas,
    /* Present only where two seats share one local government, and carried all
       the way to the screen: see scripts/build-constituencies.mjs. */
    shared: row.shared ?? null,
  };
}

/* Kept private rather than imported from lib/territory.js so this module has
   exactly one entry point per question. The grammar is that file's. */
function parse(text) {
  const [head, ...rest] = String(text ?? "").trim().split(":");
  const level = head.toUpperCase();
  if (!LEVELS.includes(level)) return null;
  if (level === "NATION") return { level, key: null };
  const key = rest.join(":").trim();
  return key ? { level, key } : null;
}

/**
 * What a territory contains, named, for a screen that has to show its parts.
 *
 * A list of "24/13" is a list nobody can check. This is the same list as
 * names, which is what an administrator reads before approving somebody onto
 * it and what a panel beside a map is ranked by.
 */
export function lgasOf(territory) {
  if (!territory?.lgas) return [];
  return territory.lgas.map((code) => ({ code, name: lgaNameForCode(code) ?? code }));
}
