/**
 * Roll the whole country down to its polling units, once, at build time.
 *
 *   node scripts/model-units.mjs > lib/data/units-modelled.js
 *
 * ══════════════════════════════════════════════════════════════════════════
 *  WHY THIS IS A SCRIPT AND NOT A useMemo
 *
 *  176,623 polling units across 37 files totalling 8.3MB. Apportioning every
 *  one of them takes seconds in node and would take a browser far longer,
 *  having first downloaded the whole tree — for a figure that never changes,
 *  because it is derived from an election held three years ago.
 *
 *  So it is computed here and shipped as a table of counts.
 *
 *  ── WHAT THE NUMBERS IN IT ARE, AND ARE NOT ──────────────────────────────
 *  "Atiku carried N booths" off this file is a MODELLED figure. The published
 *  state total was apportioned across that state's real wards and real booths;
 *  the parts sum back to what INEC declared, and the distribution is the shape
 *  a state of that composition has.
 *
 *  It is not a list of booths. Nobody holds one — INEC published photographs
 *  of 167,443 result sheets and no table, and the only transcription that
 *  exists covers 3,679 booths in one state. A screen drawing this must say
 *  "about N", must say modelled, and must never name a booth from it.
 * ══════════════════════════════════════════════════════════════════════════
 */
import { readFileSync, readdirSync } from "node:fs";

import { ELECTIONS, bucketOf, modelState, unitsOfWard, winnerOf } from "../lib/strongholds.js";

const DIR = "public/geo/units";

/** Where the register sits: what share the largest slice of booths holds. */
const CUTS = [0.05, 0.1, 0.25, 0.5];

const out = {};

for (const election of ELECTIONS) {
  if (!election.stateLevel) continue;

  const slots = election.parties.map((party) => party.id);
  /* 1999 fielded two parties and no bucket. Passing this is what stops the
     second of them being skipped as one. */
  const bucket = bucketOf(slots);
  const states = [];

  for (const file of readdirSync(DIR).filter((name) => name.endsWith(".json")).sort()) {
    const book = JSON.parse(readFileSync(`${DIR}/${file}`, "utf8"));
    const model = modelState({ book, year: election.year });
    if (!model) continue;

    const won = slots.map(() => 0);
    let units = 0;
    let counted = 0;
    let registered = 0;
    const sizes = [];

    for (const ward of model.wards) {
      for (const unit of unitsOfWard({ model, wardKey: ward.key })) {
        units += 1;
        if (unit.counted) counted += 1;
        /* A booth with no transcription in a counted state has no winner and
           no size. Counting it as a loss for everybody would understate every
           party at once; leaving it out is what "unknown" means. */
        if (unit.total === null) continue;

        const winner = winnerOf(unit.votes, bucket);
        if (winner !== null) won[winner] += 1;
        registered += unit.registered ?? 0;
        sizes.push(unit.registered ?? 0);
      }
    }

    sizes.sort((a, b) => b - a);
    const whole = sizes.reduce((sum, size) => sum + size, 0);
    const concentration = CUTS.map((cut) => {
      const take = Math.max(1, Math.round(sizes.length * cut));
      const head = sizes.slice(0, take).reduce((sum, size) => sum + size, 0);
      return { cut, booths: take, share: whole > 0 ? (head / whole) * 100 : 0 };
    });

    states.push({
      code: model.code,
      state: book.state,
      name: book.name,
      units,
      /* How many of this state's booths are a transcription rather than an
         apportionment. Zero everywhere but Anambra, and the screen says so. */
      counted,
      registered,
      won,
      concentration,
    });

    process.stderr.write(`${election.year} ${book.name}: ${units} booths\n`);
  }

  out[election.year] = { slots, states };
}

process.stdout.write(`/**
 * Every polling unit in Nigeria, modelled, for each election that published a
 * table by state.
 *
 * ── MODELLED. NOT A RECORD OF ANY BOOTH ────────────────────────────────────
 * The declared state total apportioned across that state's real wards and
 * booths. The parts sum back to INEC's figure; the distribution is the shape a
 * state of that composition has. There is no published table of Nigerian
 * presidential results by polling unit, for any year, so nothing here can be
 * checked against one — and nothing here may be used to name a booth.
 *
 * \`counted\` is how many of a state's booths came from an actual transcription
 * rather than from the apportionment. It is zero for every state but Anambra.
 *
 * Generated by scripts/model-units.mjs. Do not edit by hand.
 */
export const MODELLED = ${JSON.stringify(out)};
`);
